#!/usr/bin/env bash
# GRUB theme installer with an interactive install/switch menu
set -euo pipefail

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    cat <<EOF
Usage: sudo $0 [--switch | --theme THEME | --uninstall]

  --switch          Choose a theme to install or switch to (interactive)
  --theme THEME     Install or switch directly to a bundled theme
  --uninstall       Remove the active bundled theme and GRUB_THEME setting
EOF
    exit 0
fi

[ "$EUID" -eq 0 ] || { echo "Run with sudo."; exit 1; }

GRUB_CFG="/etc/default/grub"
THEMES_DIR="$(cd "$(dirname "$0")" && pwd)/themes"

# Detect GRUB config command and themes install path.
if [ -d /boot/grub2 ]; then
    GRUB_THEMES="/boot/grub2/themes"
    MKCONFIG=(grub2-mkconfig -o /boot/grub2/grub.cfg)
else
    GRUB_THEMES="/boot/grub/themes"
    if command -v update-grub >/dev/null; then
        MKCONFIG=(update-grub)
    elif command -v grub-mkconfig >/dev/null; then
        MKCONFIG=(grub-mkconfig -o /boot/grub/grub.cfg)
    else
        echo "Could not find update-grub or grub-mkconfig." >&2
        exit 1
    fi
fi

LOCKED_THEMES=(marquardt mq)
ACCESS_KEY="interns@mqi2025"

THEMES=()
for dir in "$THEMES_DIR"/*/; do
    [ -d "$dir" ] || continue
    THEMES+=("$(basename "$dir")")
done
if [ "${#THEMES[@]}" -eq 0 ]; then
    echo "No theme folders were found in $THEMES_DIR." >&2
    exit 1
fi

# Match only exact GRUB_THEME values generated by this installer. Never derive
# a recursive-delete path from unchecked text in /etc/default/grub.
CURRENT_THEME=""
if [ -f "$GRUB_CFG" ]; then
    for name in "${THEMES[@]}"; do
        expected="$GRUB_THEMES/$name/theme.txt"
        if grep -Fxq "GRUB_THEME=\"$expected\"" "$GRUB_CFG" ||
           grep -Fxq "GRUB_THEME=$expected" "$GRUB_CFG"; then
            CURRENT_THEME="$name"
            break
        fi
    done
fi

if [ "${1:-}" = "--uninstall" ]; then
    if [ -n "$CURRENT_THEME" ]; then
        rm -rf -- "$GRUB_THEMES/$CURRENT_THEME"
        echo "Removed theme files for '$CURRENT_THEME'."
    else
        echo "No active bundled theme path was found; leaving theme directories untouched."
    fi
    if [ -f "$GRUB_CFG" ]; then
        sed -i '/^GRUB_THEME=/d' "$GRUB_CFG"
    else
        echo "GRUB configuration file not found: $GRUB_CFG" >&2
        exit 1
    fi
    "${MKCONFIG[@]}"
    echo "Uninstalled. Reboot to apply."
    exit 0
fi

case "${1:-}" in
    ""|--switch)
        if [ "$#" -gt 1 ]; then
            echo "Usage: sudo $0 [--switch | --theme THEME | --uninstall]" >&2
            exit 2
        fi
        echo ""
        echo "Current theme: ${CURRENT_THEME:-none detected}"
        echo "Choose a theme to install or switch to:"
        for i in "${!THEMES[@]}"; do
            name="${THEMES[$i]}"
            suffix=""
            for locked in "${LOCKED_THEMES[@]}"; do
                if [ "$name" = "$locked" ]; then
                    suffix=" [access key required]"
                fi
            done
            if [ "$name" = "$CURRENT_THEME" ]; then
                suffix+=" [currently active]"
            fi
            echo "  $((i+1))) $name$suffix"
        done
        echo ""
        read -rp "Select a theme [1-${#THEMES[@]}]: " choice
        if ! [[ "$choice" =~ ^[0-9]+$ ]] ||
           [ "$choice" -lt 1 ] || [ "$choice" -gt "${#THEMES[@]}" ]; then
            echo "Invalid choice." >&2
            exit 1
        fi
        THEME="${THEMES[$((choice-1))]}"
        ;;
    --theme)
        if [ "$#" -ne 2 ]; then
            echo "Usage: sudo $0 --theme THEME" >&2
            exit 2
        fi
        THEME="$2"
        valid_theme=false
        for name in "${THEMES[@]}"; do
            if [ "$THEME" = "$name" ]; then
                valid_theme=true
                break
            fi
        done
        if [ "$valid_theme" != true ]; then
            echo "Unknown theme '$THEME'. Choose one of: ${THEMES[*]}" >&2
            exit 1
        fi
        ;;
    *)
        echo "Unknown option '$1'. Use --help for usage." >&2
        exit 2
        ;;
esac

# Locked themes require their access key before installation.
for locked in "${LOCKED_THEMES[@]}"; do
    if [ "$THEME" = "$locked" ]; then
        read -rsp "Enter access key for '$THEME': " key
        echo
        if [ "$key" != "$ACCESS_KEY" ]; then
            echo "Invalid access key." >&2
            exit 1
        fi
    fi
done

SRC="$THEMES_DIR/$THEME"
DEST="$GRUB_THEMES/$THEME"
if [ ! -f "$SRC/theme.txt" ]; then
    echo "Theme '$THEME' is missing theme.txt." >&2
    exit 1
fi
if [ ! -f "$GRUB_CFG" ]; then
    echo "GRUB configuration file not found: $GRUB_CFG" >&2
    exit 1
fi

echo "Installing or switching to theme: $THEME"
mkdir -p "$DEST"
cp -r "$SRC/"* "$DEST/"

cp -n "$GRUB_CFG" "${GRUB_CFG}.bak-grubtheme" 2>/dev/null || true

if grep -q '^GRUB_THEME=' "$GRUB_CFG"; then
    sed -i "s|^GRUB_THEME=.*|GRUB_THEME=\"$DEST/theme.txt\"|" "$GRUB_CFG"
else
    echo "GRUB_THEME=\"$DEST/theme.txt\"" >> "$GRUB_CFG"
fi

grep -q '^GRUB_GFXMODE=' "$GRUB_CFG" || echo 'GRUB_GFXMODE=1920x1080,auto' >> "$GRUB_CFG"
sed -i 's|^GRUB_TERMINAL_OUTPUT=|#GRUB_TERMINAL_OUTPUT=|' "$GRUB_CFG"

"${MKCONFIG[@]}"
echo ""
echo "Theme '$THEME' is configured. Reboot to apply."
echo "To switch themes: sudo $0 --switch"
echo "To uninstall: sudo $0 --uninstall"
