#!/usr/bin/env bash
# GRUB theme installer with an interactive install/switch menu
set -euo pipefail

DEFAULT_TIMEOUT=30

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    cat <<EOF
Usage: sudo $0 [--switch | --theme THEME | --uninstall] [--timeout SECONDS]

  --switch          Activate a theme whose files are already installed
  --theme THEME     Install or switch directly to a bundled theme
  --timeout SECONDS How long the boot menu waits before auto-booting
                    (default: $DEFAULT_TIMEOUT). Only used together with
                    --theme, or the plain install/switch menu.
  --uninstall       Remove the active bundled theme and GRUB_THEME setting
EOF
    exit 0
fi

[ "$EUID" -eq 0 ] || { echo "Run with sudo."; exit 1; }

GRUB_CFG="/etc/default/grub"
THEMES_DIR="$(cd "$(dirname "$0")" && pwd)/themes"
TIMEOUT=""

# Pull a --timeout SECONDS pair out of the argument list wherever it appears,
# leaving the remaining arguments (--switch / --theme THEME / --uninstall) untouched.
ARGS=()
while [ "$#" -gt 0 ]; do
    case "$1" in
        --timeout)
            [ "$#" -ge 2 ] || { echo "--timeout needs a value in seconds." >&2; exit 2; }
            TIMEOUT="$2"
            shift 2
            ;;
        *)
            ARGS+=("$1")
            shift
            ;;
    esac
done
set -- "${ARGS[@]+"${ARGS[@]}"}"
if [ -n "$TIMEOUT" ] && ! [[ "$TIMEOUT" =~ ^[0-9]+$ ]]; then
    echo "--timeout must be a whole number of seconds." >&2
    exit 2
fi

# Detect GRUB config command and themes install path.
if [ -d /boot/grub2 ]; then
    GRUB_THEMES="/boot/grub2/themes"
    MKCONFIG=(grub2-mkconfig -o /boot/grub2/grub.cfg)
else
    GRUB_THEMES="/boot/grub/themes"
    if command -v update-grub >/dev/null; then
        MKCONFIG=(update-grub)
    elif command -v grub-mkconfig >/dev/null; then
        MKCONFIG=(grub-mkconfig -o /boot/grub/grub.cfg)
    else
        echo "Could not find update-grub or grub-mkconfig." >&2
        exit 1
    fi
fi

LOCKED_THEMES=(marquardt mq)
ACCESS_KEY="interns@mqi2025"

# Set how long the graphical menu waits before auto-booting, and make sure the
# menu (and its countdown) is actually shown: many distros ship
# GRUB_TIMEOUT_STYLE=hidden, which would keep a theme from ever appearing.
# With no explicit $1, an existing non-zero GRUB_TIMEOUT is left alone (so
# switching themes doesn't quietly reset a timeout you already chose); a
# missing or 0 timeout (Ubuntu's default) is replaced with $DEFAULT_TIMEOUT.
apply_timeout() {
    local secs="$1"
    if [ -z "$secs" ]; then
        local current
        current="$(sed -n 's/^GRUB_TIMEOUT=//p' "$GRUB_CFG" | tail -n1)"
        if [ -z "$current" ] || [ "$current" = "0" ]; then
            secs="$DEFAULT_TIMEOUT"
        else
            secs="$current"
        fi
    fi
    if grep -q '^GRUB_TIMEOUT=' "$GRUB_CFG"; then
        sed -i "s|^GRUB_TIMEOUT=.*|GRUB_TIMEOUT=$secs|" "$GRUB_CFG"
    else
        echo "GRUB_TIMEOUT=$secs" >> "$GRUB_CFG"
    fi
    if grep -q '^GRUB_TIMEOUT_STYLE=' "$GRUB_CFG"; then
        sed -i "s|^GRUB_TIMEOUT_STYLE=.*|GRUB_TIMEOUT_STYLE=menu|" "$GRUB_CFG"
    else
        echo "GRUB_TIMEOUT_STYLE=menu" >> "$GRUB_CFG"
    fi
}

# GRUB does not look inside a theme folder for fonts on its own, so drop a
# grub.d script that loads the theme's .pf2 files. The script's only job at
# boot-config-generation time is to print a few grub commands to stdout,
# which grub-mkconfig folds into the final grub.cfg (same trick 40_custom
# uses with "exec tail").
write_font_loader() {
    local dest="$1" script="/etc/grub.d/06_theme_fonts" f
    {
        printf '#!/bin/sh\n'
        printf 'cat <<'"'"'GRUBCFG'"'"'\n'
        printf 'insmod all_video\n'
        for f in "$dest"/*.pf2; do
            [ -e "$f" ] || continue
            printf 'loadfont "%s"\n' "$f"
        done
        printf 'GRUBCFG\n'
    } > "$script"
    chmod +x "$script"
}

THEMES=()
for dir in "$THEMES_DIR"/*/; do
    [ -d "$dir" ] || continue
    THEMES+=("$(basename "$dir")")
done
if [ "${#THEMES[@]}" -eq 0 ]; then
    echo "No theme folders were found in $THEMES_DIR." >&2
    exit 1
fi

# Match only exact GRUB_THEME values generated by this installer. Never derive
# a recursive-delete path from unchecked text in /etc/default/grub.
CURRENT_THEME=""
if [ -f "$GRUB_CFG" ]; then
    for name in "${THEMES[@]}"; do
        expected="$GRUB_THEMES/$name/theme.txt"
        if grep -Fxq "GRUB_THEME=\"$expected\"" "$GRUB_CFG" ||
           grep -Fxq "GRUB_THEME=$expected" "$GRUB_CFG"; then
            CURRENT_THEME="$name"
            break
        fi
    done
fi

INSTALLED_THEMES=()
NEW_THEMES=()
for name in "${THEMES[@]}"; do
    if [ -f "$GRUB_THEMES/$name/theme.txt" ]; then
        INSTALLED_THEMES+=("$name")
    else
        NEW_THEMES+=("$name")
    fi
done

select_theme_from() {
    local prompt="$1"
    shift
    local -a choices=("$@")
    local i name suffix locked

    if [ "${#choices[@]}" -eq 0 ]; then
        echo "No themes are available for this action." >&2
        return 1
    fi

    echo ""
    echo "$prompt"
    for i in "${!choices[@]}"; do
        name="${choices[$i]}"
        suffix=""
        for locked in "${LOCKED_THEMES[@]}"; do
            if [ "$name" = "$locked" ]; then
                suffix=" [access key required]"
            fi
        done
        if [ "$name" = "$CURRENT_THEME" ]; then
            suffix+=" [currently active]"
        fi
        echo "  $((i+1))) $name$suffix"
    done
    echo ""
    read -rp "Select a theme [1-${#choices[@]}]: " choice || {
        echo "No theme selection was entered." >&2
        return 1
    }
    if ! [[ "$choice" =~ ^[0-9]+$ ]] ||
       [ "$choice" -lt 1 ] || [ "$choice" -gt "${#choices[@]}" ]; then
        echo "Invalid choice." >&2
        return 1
    fi
    THEME="${choices[$((choice-1))]}"
}

if [ "${1:-}" = "--uninstall" ]; then
    if [ -n "$CURRENT_THEME" ]; then
        rm -rf -- "$GRUB_THEMES/$CURRENT_THEME"
        echo "Removed theme files for '$CURRENT_THEME'."
    else
        echo "No active bundled theme path was found; leaving theme directories untouched."
    fi
    rm -f /etc/grub.d/06_theme_fonts
    if [ -f "$GRUB_CFG" ]; then
        sed -i '/^GRUB_THEME=/d' "$GRUB_CFG"
    else
        echo "GRUB configuration file not found: $GRUB_CFG" >&2
        exit 1
    fi
    "${MKCONFIG[@]}"
    echo "Uninstalled. Reboot to apply."
    exit 0
fi

# `--timeout SECONDS` with nothing else just updates the countdown for
# whatever theme is already active, without touching theme selection.
if [ -n "$TIMEOUT" ] && [ "$#" -eq 0 ]; then
    if [ -z "$CURRENT_THEME" ]; then
        echo "No active bundled theme found. Use --theme THEME --timeout SECONDS to install one with this timeout." >&2
        exit 1
    fi
    if [ ! -f "$GRUB_CFG" ]; then
        echo "GRUB configuration file not found: $GRUB_CFG" >&2
        exit 1
    fi
    cp -n "$GRUB_CFG" "${GRUB_CFG}.bak-grubtheme" 2>/dev/null || true
    apply_timeout "$TIMEOUT"
    write_font_loader "$GRUB_THEMES/$CURRENT_THEME"
    "${MKCONFIG[@]}"
    echo ""
    echo "Boot timeout updated to ${TIMEOUT}s for theme '$CURRENT_THEME'. Reboot to apply."
    exit 0
fi

case "${1:-}" in
    "")
        if [ "$#" -gt 1 ]; then
            echo "Usage: sudo $0 [--switch | --theme THEME | --uninstall]" >&2
            exit 2
        fi
        echo ""
        if [ -n "$CURRENT_THEME" ]; then
            echo "Current installed theme: $CURRENT_THEME"
            echo "What would you like to do?"
            echo "  1) Install a new theme"
            echo "  2) Change the current theme (choose from installed themes)"
            read -rp "Choose an action [1-2]: " action || {
                echo "No action was selected." >&2
                exit 1
            }
            case "$action" in
                1)
                    if [ "${#NEW_THEMES[@]}" -eq 0 ]; then
                        echo "All bundled themes are already installed; choose one to reinstall."
                        select_theme_from "Select a theme to reinstall" "${THEMES[@]}"
                    else
                        select_theme_from "Select a new theme to install" "${NEW_THEMES[@]}"
                    fi
                    ;;
                2)
                    select_theme_from "Select an installed theme to activate" "${INSTALLED_THEMES[@]}"
                    ;;
                *)
                    echo "Invalid action." >&2
                    exit 1
                    ;;
            esac
        elif [ "${#INSTALLED_THEMES[@]}" -gt 0 ]; then
            echo "No active bundled theme is configured."
            echo "  1) Install a new theme"
            echo "  2) Activate a theme that is already installed"
            read -rp "Choose an action [1-2]: " action || {
                echo "No action was selected." >&2
                exit 1
            }
            case "$action" in
                1)
                    if [ "${#NEW_THEMES[@]}" -eq 0 ]; then
                        select_theme_from "Select a theme to reinstall" "${THEMES[@]}"
                    else
                        select_theme_from "Select a new theme to install" "${NEW_THEMES[@]}"
                    fi
                    ;;
                2) select_theme_from "Select an installed theme to activate" "${INSTALLED_THEMES[@]}" ;;
                *) echo "Invalid action." >&2; exit 1 ;;
            esac
        else
            echo "No bundled theme is installed yet."
            select_theme_from "Select a theme to install" "${THEMES[@]}"
        fi
        ;;
    --switch)
        if [ "$#" -ne 1 ]; then
            echo "Usage: sudo $0 --switch" >&2
            exit 2
        fi
        echo "Current installed theme: ${CURRENT_THEME:-none detected}"
        select_theme_from "Select an installed theme to activate" "${INSTALLED_THEMES[@]}"
        ;;
    --theme)
        if [ "$#" -ne 2 ]; then
            echo "Usage: sudo $0 --theme THEME" >&2
            exit 2
        fi
        THEME="$2"
        valid_theme=false
        for name in "${THEMES[@]}"; do
            if [ "$THEME" = "$name" ]; then
                valid_theme=true
                break
            fi
        done
        if [ "$valid_theme" != true ]; then
            echo "Unknown theme '$THEME'. Choose one of: ${THEMES[*]}" >&2
            exit 1
        fi
        ;;
    *)
        echo "Unknown option '$1'. Use --help for usage." >&2
        exit 2
        ;;
esac

# Locked themes require their access key before installation.
for locked in "${LOCKED_THEMES[@]}"; do
    if [ "$THEME" = "$locked" ]; then
        read -rsp "Enter access key for '$THEME': " key
        echo
        if [ "$key" != "$ACCESS_KEY" ]; then
            echo "Invalid access key." >&2
            exit 1
        fi
    fi
done

SRC="$THEMES_DIR/$THEME"
DEST="$GRUB_THEMES/$THEME"
if [ ! -f "$SRC/theme.txt" ]; then
    echo "Theme '$THEME' is missing theme.txt." >&2
    exit 1
fi
if [ ! -f "$GRUB_CFG" ]; then
    echo "GRUB configuration file not found: $GRUB_CFG" >&2
    exit 1
fi

echo "Installing or switching to theme: $THEME"
mkdir -p "$DEST"
cp -r "$SRC/"* "$DEST/"

cp -n "$GRUB_CFG" "${GRUB_CFG}.bak-grubtheme" 2>/dev/null || true

if grep -q '^GRUB_THEME=' "$GRUB_CFG"; then
    sed -i "s|^GRUB_THEME=.*|GRUB_THEME=\"$DEST/theme.txt\"|" "$GRUB_CFG"
else
    echo "GRUB_THEME=\"$DEST/theme.txt\"" >> "$GRUB_CFG"
fi

grep -q '^GRUB_GFXMODE=' "$GRUB_CFG" || echo 'GRUB_GFXMODE=1920x1080,auto' >> "$GRUB_CFG"
sed -i 's|^GRUB_TERMINAL_OUTPUT=|#GRUB_TERMINAL_OUTPUT=|' "$GRUB_CFG"

apply_timeout "$TIMEOUT"
write_font_loader "$DEST"

"${MKCONFIG[@]}"
APPLIED_TIMEOUT="$(sed -n 's/^GRUB_TIMEOUT=//p' "$GRUB_CFG" | tail -n1)"
echo ""
echo "Theme '$THEME' is configured with a ${APPLIED_TIMEOUT}s boot timeout. Reboot to apply."
echo "To change just the timeout later: sudo $0 --timeout SECONDS"
echo "To switch themes: sudo $0 --switch"
echo "To uninstall: sudo $0 --uninstall"
