#!/usr/bin/env python3
"""Generate src/assets.h: anti-aliased font atlases, logo alpha map, sine table.

Usage:  python3 tools/gen_assets.py [--logo assets/logo.png] [--logo-mode alpha|white-on-color|dark-on-light]
Needs:  pip install pillow numpy   and the Poppins TTFs (SIL OFL) in assets/fonts/.
"""
import argparse, math, os, sys
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ap = argparse.ArgumentParser()
ap.add_argument("--logo", default="assets/logo.png")
ap.add_argument("--logo-mode", default="alpha", choices=["alpha", "white-on-color", "dark-on-light"])
ap.add_argument("--logo-height", type=int, default=0, help="rescale stored logo to this height (0 = keep)")
ap.add_argument("--out", default="src/assets.h")
args = ap.parse_args()

def find(name):
    for d in ["assets/fonts", "/usr/share/fonts/truetype/google-fonts", "/usr/share/fonts/truetype/poppins"]:
        p = os.path.join(d, name)
        if os.path.exists(p): return p
    sys.exit(f"font {name} not found; put it in assets/fonts/")

FONTS = [("SMALL", "Poppins-Medium.ttf", 26), ("BODY", "Poppins-Medium.ttf", 38), ("BIG", "Poppins-Bold.ttf", 66)]
CHARS = [chr(c) for c in range(32, 127)]

out = ["/* GENERATED by tools/gen_assets.py - do not edit */", "#pragma once", "#include <stdint.h>",
       "typedef struct { uint32_t off; uint8_t w, h; int8_t bx, by; uint8_t adv; } Glyph;",
       "typedef struct { int px, ascent, line; const Glyph *g; const uint8_t *bmp; } Font;", ""]

for name, ttf, size in FONTS:
    f = ImageFont.truetype(find(ttf), size)
    asc, desc = f.getmetrics()
    blob, glyphs = bytearray(), []
    for ch in CHARS:
        adv = int(round(f.getlength(ch)))
        bb = f.getbbox(ch, anchor="ls")
        w, h = bb[2] - bb[0], bb[3] - bb[1]
        if ch == " " or w <= 0 or h <= 0:
            glyphs.append((len(blob), 0, 0, 0, 0, adv)); continue
        im = Image.new("L", (w, h), 0)
        ImageDraw.Draw(im).text((-bb[0], -bb[1]), ch, font=f, fill=255, anchor="ls")
        glyphs.append((len(blob), w, h, bb[0], -bb[1], adv))
        blob += im.tobytes()
    out.append(f"static const uint8_t font_{name}_bmp[] = {{" + ",".join(map(str, blob)) + "};")
    out.append(f"static const Glyph font_{name}_g[] = {{" + ",".join("{%d,%d,%d,%d,%d,%d}" % g for g in glyphs) + "};")
    out.append(f"static const Font FONT_{name} = {{ {size}, {asc}, {asc+desc}, font_{name}_g, font_{name}_bmp }};\n")

im = Image.open(args.logo).convert("RGBA")
a = np.asarray(im).astype(float)
if args.logo_mode == "alpha":
    alpha = a[..., 3] / 255.0
elif args.logo_mode == "white-on-color":
    alpha = np.clip((a[..., 0] - 40) / 215.0, 0, 1)
else:
    alpha = np.clip((255 - a[..., :3].mean(axis=2) - 30) / 200.0, 0, 1)
al = Image.fromarray((alpha * 255).astype("uint8"))
bb = al.point(lambda v: 255 if v > 24 else 0).getbbox()
if bb: al = al.crop(bb)
if args.logo_height:
    al = al.resize((max(1, round(al.width * args.logo_height / al.height)), args.logo_height), Image.LANCZOS)
lw, lh = al.size
out.append(f"#define LOGO_W {lw}\n#define LOGO_H {lh}")
out.append("static const uint8_t logo_alpha[] = {" + ",".join(map(str, al.tobytes())) + "};\n")
out.append("static const int16_t sintab[256] = {" + ",".join(str(int(round(math.sin(i * 2 * math.pi / 256) * 1024))) for i in range(256)) + "};")
open(args.out, "w").write("\n".join(out) + "\n")
print(f"wrote {args.out}: logo {lw}x{lh}")
