# Marquardt build config -> <ESP>\EFI\AuroraBoot\aurora.conf
title      = Marquardt
subtitle   = Select operating system
timeout    = 8
default    = windows
accent     = #009AA6
accent2    = #0B4F5C
show_title = false
show_system_items = true
