#!/usr/bin/env python3
"""Generate the GRUB themes in ../themes (backgrounds, glass selection boxes, OS icons, fonts, theme.txt).

    python3 tools/gen_grub_themes.py            # all themes
    python3 tools/gen_grub_themes.py aurora mq  # only these

Needs: pip install pillow numpy   and   grub-mkfont (package grub-common) for the Poppins .pf2 fonts.
Every theme has its own layout, selection style, icons and countdown widget: they are not palette swaps.
"""
import os, subprocess, sys, shutil, math
import numpy as np
from PIL import Image, ImageDraw
import gfxlib as G
from gfxlib import W, H, rgb

ROOT = G.ROOT
OUT = os.path.join(ROOT, "themes")

FONT_SPECS = [  # (file, family, bold flag, sizes)
    ("Poppins-Medium.ttf", "ABText", False, [18, 20, 22, 24, 26]),
    ("Poppins-Bold.ttf", "ABText", True, [20, 22, 24, 26, 30, 44]),
]


def build_fonts(dest):
    for fname, fam, bold, sizes in FONT_SPECS:
        for sz in sizes:
            out = os.path.join(dest, f"abtext-{'bold' if bold else 'reg'}-{sz}.pf2")
            cmd = ["grub-mkfont", "-n", fam, "-s", str(sz), "-o", out, G.find_font(fname)]
            if bold:
                cmd.insert(1, "-b")
            subprocess.run(cmd, check=True, stderr=subprocess.DEVNULL)


def hexs(c):
    return c if isinstance(c, str) else "#%02x%02x%02x" % tuple(int(v * 255) for v in c)


def write_theme_txt(dest, t):
    L = t["layout"]
    m = L["menu"]
    lines = [f"# {t['title']} GRUB theme  (generated by tools/gen_grub_themes.py)",
             'desktop-image: "background.png"',
             f'desktop-color: "{t["desktop_color"]}"',
             'title-text: ""',
             'terminal-font: "Unifont Regular 16"',
             'terminal-left: "0"', 'terminal-top: "0"', 'terminal-width: "100%"', 'terminal-height: "100%"',
             'terminal-border: "0"', ""]
    lines += ["+ boot_menu {",
              f'    left = {m["left"]}', f'    top = {m["top"]}', f'    width = {m["width"]}', f'    height = {m["height"]}',
              f'    item_font = "{t["font_item"]}"', f'    selected_item_font = "{t["font_sel"]}"',
              f'    item_color = "{t["item_color"]}"', f'    selected_item_color = "{t["sel_color"]}"',
              f'    item_height = {m["item_h"]}', f'    item_padding = {m["pad"]}', f'    item_spacing = {m["spacing"]}',
              f'    item_icon_space = {m["icon_space"]}', f'    icon_width = {m["icon"]}', f'    icon_height = {m["icon"]}',
              '    item_pixmap_style = "item_*.png"', '    selected_item_pixmap_style = "select_*.png"',
              '    scrollbar = false', "}", ""]
    p = L["progress"]
    if p["kind"] == "bar":
        lines += ["+ progress_bar {", '    id = "__timeout__"',
                  f'    left = {p["left"]}', f'    top = {p["top"]}', f'    width = {p["width"]}', f'    height = {p["height"]}',
                  '    show_text = false', 'bar_style = "trough_*.png"', '    highlight_style = "fill_*.png"',
                  f'    fg_color = "{t["accent"]}"', f'    bg_color = "{t["trough"]}"', f'    border_color = "{t["trough"]}"', "}", ""]
    else:
        lines += ["+ circular_progress {", '    id = "__timeout__"',
                  f'    left = {p["left"]}', f'    top = {p["top"]}', f'    width = {p["size"]}', f'    height = {p["size"]}',
                  '    num_ticks = 60', '    start_angle = -64', '    end_angle = 200',
                  '    center_bitmap = "ring_bg.png"', '    tick_bitmap = "tick.png"', "}", ""]
    c = L["countdown"]
    lines += ["+ label {", '    id = "__timeout__"',
              f'    left = {c["left"]}', f'    top = {c["top"]}', f'    width = {c["width"]}', f'    height = {c.get("height", 30)}',
              f'    align = "{c["align"]}"', f'    text = "{c["text"]}"',
              f'    color = "{t["countdown_color"]}"', f'    font = "{t["font_small"]}"', "}", ""]
    open(os.path.join(dest, "theme.txt"), "w", newline="\n").write("\n".join(lines))


def build(name, t):
    dest = os.path.join(OUT, name)
    if os.path.isdir(dest):
        for f in os.listdir(dest):
            p = os.path.join(dest, f)
            (shutil.rmtree if os.path.isdir(p) else os.remove)(p)
    os.makedirs(dest, exist_ok=True)
    img = t["paint"]()
    G.to_img(img).save(os.path.join(dest, "background.png"), optimize=True)
    for spec in t["boxes"]:
        G.write_box(dest, **spec)
    G.write_icons(os.path.join(dest, "icons"), t["layout"]["menu"]["icon"], t["accent"], t.get("icon_blend", 0.28))
    for extra in t.get("extra", []):
        extra(dest)
    build_fonts(dest)
    write_theme_txt(dest, t)
    print(f"  {name}: done")


sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import themes_def  # noqa: E402

if __name__ == "__main__":
    want = sys.argv[1:] or list(themes_def.THEMES)
    for n in want:
        build(n, themes_def.THEMES[n]())
